#server port config
server:
  port: 8090

jwt.secret.key: secretKey
#database config
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
#    username: root
#    password: 13AntiviruS46
#  
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: update
#    defer-datasource-initialization: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 13AntiviruS46
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true